### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Makgora** [Makgora/TodoList#1]
- [x] Rapport
- [x] Javadoc
- [x] Lier les bouttons avec les fonctionnalités
- [x] Interface de gestion category
- [x] Code en Anglais
- [x] LongTask
- [x] Deuxième tri des taches
- [x] Diagrammes Classe etc
- [x] Edition de bilan
- [x] Test
